language: node_js
node_js:
  - "node"
dist: trusty
sudo: false
cache:
  directories:
    - node_modules

before_install:
  - npm -g install create-elm-app

install:
  - npm install
  - cd example
  - npm install
  - npm run build
  - travis_wait elm-app build