version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo npm -g install elm@0.19.0-bugfix2 --unsafe-perm=true --allow-root
            - run: sudo npm -g install elm-test@0.19.0-rev3 --unsafe-perm=true --allow-root
            - run: sudo npm -g install create-elm-app@2.2.3 --unsafe-perm=true --allow-root
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
